services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi_app/Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    container_name: streamlit_container
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi
